version: '3.8'

services:
  db:
    image: postgres:latest
    #container_name: db_pg1
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_DB: ostock_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
     # - /home/progforce/amazonServerless/config_sefver/DB_config:/var/lib/postgresql/data

    